name: Deploy to scalingo

on:
  repository_dispatch:
    types: [trigger-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SCALINGO }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-agent bash -c 'ssh-add ~/.ssh/id_rsa; ssh-keyscan ssh.osc-fr1.scalingo.com >> ~/.ssh/known_hosts'
          ssh -vT git@ssh.osc-fr1.scalingo.com

      - name: Display Git remotes
        run: git remote -v

      - name: Deploy to Scalingo
        run: |
          git remote add scalingo git@ssh.osc-fr1.scalingo.com:python-api.git
          git push scalingo HEAD:master
