name: deploy to scalingo

on:
  repository_dispatch:
    types: [trigger-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Scalingo
        uses: kolok/deploy-to-scalingo@v1
        with:
          scalingo_token: ${{ secrets.SCALINGO_TOKEN }}
          app_name: python-api

